### ISSUE TITLE
Should encode the URL before calling `curl`

### ISSUE THREAD

**Issue by vincejv** [ricardotx/transmission-telegram-notifications#1]
Should encode the URL before calling `curl` or else it will error out, even the html `<strong/>` tag isn't a valid character in the script provided in the repo, not sure if this was tested or worked in earlier version of curl
```shell
curl: (3) URL rejected: Malformed input to a URL function
[]-[] Download completed. Telegram notification sent.
```

**Comment by vincejv** [comment]
can we modify the curl command to encode the url as described in [this stackoverflow answer](https://stackoverflow.com/questions/296536/how-to-urlencode-data-for-curl-command)?
```shell
curl --get \
    --data-urlencode "p1=value 1" \
    --data-urlencode "p2=value 2" \
    http://example.com
    # http://example.com?p1=value%201&p2=value%202
```
will try to push a PR if the maintainer is busy, also we should remove the `sudo` in `tee`, apply the changes to https://github.com/rteixeirax/qbittorrent_telegram_notification as well

**Comment by rteixeirax** [comment]
Hi @vincejv, thanks for reporting the issue. Feel free to open a PR with that change.
